name: linearmodel continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_deps()

      - name: Run tests
        run: |
          library(testthat)
          test_check("myLM3")

      - name: Check package
        run: |
          R CMD check .
